fix: self-update in parallel processes does not work properly
Add 30 seconds delay between updates due to there is no proper way to prevent the following possible errors during parallel updates:
```
# unix: attempt to update current program path that points to non-existent file after the parallel self-update
Error: rename /home/user/go/bin/.trdl.old /home/user/go/bin/..trdl.old.old: no such file or directory

# windows: attempt to replace real current binary file (.trdl.exe.old) with the result binary file (trdl.exe) from the parallel self-update
Error: rename C:\Users\user\go\bin\trdl.exe C:\Users\user\go\bin\.trdl.exe.old: Access is denied.
```